name: GamaManyInputsSandbox
on:
  workflow_dispatch:
    inputs:
      parameters:
        description: "JSON Parameters"
        required: true
        default: '{
          "param01": "Paramter 1",
          "param02": "Paramter 2",
          "param03": "Paramter 3",
          "param04": "Paramter 4",
          "param05": "Paramter 5",
          "param06": "Paramter 6",
          "param07": "Paramter 7",
          "param08": "Paramter 8",
          "param09": "Paramter 9",
          "param10": "Paramter 10",
          "param11": "Paramter 11",
          "param12": "Paramter 12",
          "param13": "Paramter 13",
          "param14": "Paramter 14",
          "param15": "Paramter 15",
          "param16": "Paramter 16",
          "param17": "Paramter 17",
          "param18": "Paramter 18",
          "param19": "Paramter 19",
          "param20": "Paramter 20"
          }'

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo parameters
        run: |
          echo ${{ fromJson(inputs.parameters).param01 }}
          echo ${{ fromJson(inputs.parameters).param02 }}
          echo ${{ fromJson(inputs.parameters).param03 }}
          echo ${{ fromJson(inputs.parameters).param04 }}
          echo ${{ fromJson(inputs.parameters).param05 }}
          echo ${{ fromJson(inputs.parameters).param06 }}
          echo ${{ fromJson(inputs.parameters).param07 }}
          echo ${{ fromJson(inputs.parameters).param08 }}
          echo ${{ fromJson(inputs.parameters).param09 }}
          echo ${{ fromJson(inputs.parameters).param10 }}
          echo ${{ fromJson(inputs.parameters).param11 }}
          echo ${{ fromJson(inputs.parameters).param12 }}
          echo ${{ fromJson(inputs.parameters).param13 }}
          echo ${{ fromJson(inputs.parameters).param14 }}
          echo ${{ fromJson(inputs.parameters).param15 }}
          echo ${{ fromJson(inputs.parameters).param16 }}
          echo ${{ fromJson(inputs.parameters).param17 }}
          echo ${{ fromJson(inputs.parameters).param18 }}
          echo ${{ fromJson(inputs.parameters).param19 }}
          echo ${{ fromJson(inputs.parameters).param20 }}
