name: Lint

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  actionlint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            github:
              - ".github/**"
      - uses: reviewdog/action-actionlint@v1
        if: ${{ steps.filter.outputs.github == 'true' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
